nelmio_api_doc:
    documentation:
        info:
            title: BileMo
            description: mobile platforme
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/user # Accepts routes under /api except /api/doc
            - ^/client
            - ^/login
            - ^/logout
            - ^/phone 
            - ^/relation